options:
  dynamic_substitutions: true
  env:
    - "GOPATH=$_GOPATH"
    - "GOCACHE=$_GOCACHE"
    - "GOTMPDIR=$_GOTMPDIR"
substitutions:
  _BAZEL_IMAGE : "gcr.io/cloud-builders/bazel:6.2.1"
  _GO_IMAGE : "golang:1.21"
  _GOPATH : "/workspace/go"
  _GOCACHE : "/workspace/go/cache"
  _GOTMPDIR : "/workspace/go/tmp"
  _PROJECT : "subtle-canto-412404"
  _REGION : "us-central1"
  _APP_IMAGE : "ubuntu"
  _SERVICE : "stox"
  _DEPLOYMENT : "qa"
  _GITHUB_REPO : "https://github.com/t-hale/stox"
  _SERVICE_ACCOUNT : "infrastructure@subtle-canto-412404.iam.gserviceaccount.com"
steps:
  - id: "Deploy cloud infrastructure"
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: "gcloud"
    args:
      - 'infra-manager'
      - 'deployments'
      - 'apply'
      - 'projects/$_PROJECT/locations/$_REGION/deployments/$_DEPLOYMENT'
      - '--service-account'
      - 'projects/$_PROJECT/serviceAccounts/$_SERVICE_ACCOUNT'
      - '--git-source-repo=$_GITHUB_REPO'
      - '--git-source-directory=terraform'
      - '--git-source-ref=master'
