options:
  dynamic_substitutions: true
  env:
    - "GOPATH=$_GOPATH"
    - "GOCACHE=$_GOCACHE"
    - "GOTMPDIR=$_GOTMPDIR"
substitutions:
  _BAZEL_IMAGE : "gcr.io/cloud-builders/bazel:6.2.1"
  _GOPATH : "/workspace/go"
  _GOCACHE : "/workspace/go/cache"
  _GOTMPDIR : "/workspace/go/tmp"
  _PROJECT : "subtle-canto-412404"
  _APP_IMAGE : "ubuntu"
steps:
  - id: "Build the stox server"
    name: "$_BAZEL_IMAGE"
    args: [ "build", "cmd/server" ]
  - id: "Copy server binary to PWD"
    name: "bash"
    script: |
      #!/usr/bin/env bash
      cp ./bazel-bin/cmd/server/server_/server .
  - id: "Build the container image"
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$_PROJECT/$_APP_IMAGE:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$_PROJECT/$_APP_IMAGE:latest'
      - '--build-arg'
      - 'port=8080'
      - '.'
  - id: Update the qa tag
    name: "bash"
    script: |
      #!/usr/bin/env bash
      git tag -f qa
      git push origin qa
images:
  - "gcr.io/$_PROJECT/$_APP_IMAGE:$COMMIT_SHA"
  - "gcr.io/$_PROJECT/$_APP_IMAGE:latest"
