#name: GitHub Actions Demo
#run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
#on: [push]
#jobs:
#  pull-request-status-checks:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Setup env vars
#        run: |
#          echo "GOPATH=/home/runner/go" >> "$GITHUB_ENV"
#          echo "PATH=$PATH:/home/runner/go/bin" >> "$GITHUB_ENV"
#      - name: Checkout codebase
#        uses: actions/checkout@v4
#      - name: Install goa
#        run: go install goa.design/goa/v3/cmd/goa@v3
#      - name: Generate Server, CLI and Service definitions
#        run: goa gen github.com/t-hale/stox/design
#      - name: Run gazelle to generate BUILD files
#        run: bazel run //:gazelle
#      - name: Build the stox service
#        run: bazel build :stox
#        run:  bazel run :stox_test
#      - name: Run unit tests

steps:
  # Run gazelle
  - name : 'gcr.io/cloud-builders/bazel'
    args : ['run', '//:gazelle']
  # Build the stox service
  - name : 'gcr.io/cloud-buildres/bazel'
    args : ['build', ':stox']

options:
  logging: CLOUD_LOGGING_ONLY
