name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  pull-request-status-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Setup env vars
        run: |
          echo "GOPATH=/home/runner/go" >> "$GITHUB_ENV"
          echo "PATH=$PATH:/home/runner/go/bin" >> "$GITHUB_ENV"
      - name: Checkout codebase
        uses: actions/checkout@v4
      - name: Install goa
        run: go install goa.design/goa/v3/cmd/goa@v3
      - name: Generate Server, CLI and Service definitions
        run: goa gen github.com/t-hale/stox/design
      - name: Run gazelle to generate BUILD files
        run: bazel run //:gazelle
      - name: Build the stox service
        run: bazel build :stox
#      TODO : Uncomment once unit tests are passing again
#      - name: Run unit tests
#        run:  bazel run :stox_test
